# PostgreSQL - Semana 1
spring.datasource.url=jdbc:postgresql://localhost:5432/auto_bom
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate - DDL AUTO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Selectores
app.tree-strategy=collections
app.storage=postgres